### ISSUE TITLE
Error Running Project

### ISSUE THREAD

**Issue by TobiAlbert** [timzprof/book-a-meal#50]
I'm having issues getting the project to run when I enter ```npm start``` in the console. The error message is ```Error: Cannot find module 'file-path/book-a-meal-1-develop/build/index.js' ```, so my guess is the build folder was not pushed to this remote repository. 

I'm fairly new to node.js, so  if there's any additional thing I need to setup prior to running the project, please let me know.

Thanks.

**Comment by timzprof** [comment]
Oh your meant to use `npm run dev` to run the development server , `npm start` is to run the production build which will be a `build` folder that's why your getting that error
